# Generated by Django 4.2.4 on 2023-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='درباره شخص'),
        ),
    ]
